[build]
target = "xtensa-esp32s2-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"

[target.riscv32imac-esp-espidf]
linker = "ldproxy"

[env]
ESP_IDF_SDKCONFIG_DEFAULTS = ".github/configs/sdkconfig.defaults"
ESP_IDF_VERSION = "v4.4.5"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]